package lk.ijse.studentsmanagement.util;

public enum Routes {
    ADMIN, COUNSELOR, ACADEMIC, LOGIN, INQUIRIES, ADD_STUDENT, VIEW_STUDENT, UPDATE_STUDENT, IQTest, MAIL_SERVICE_COUNSELOR, ENROLLMENTS, VIEW_REGISTRATION, PAYMENTS, COURSES, GDSE, CMJD, DEP, RWAD , EMAILCOUNSILOR,
    SendMailToStudentfromCounsilor, SendMailToGroupfromCounsilor, EXAMS, SCHEDULE_EXAMS, SCHEDULE_IQTEST

}