package lk.ijse.studentsmanagement.util;

public enum Routes {
    MAIN,
    COUNSELOR,
    ACADEMIC,
    LOGIN,
    INQUIRIES,
    ADD_STUDENT,
    VIEW_STUDENT,
    UPDATE_STUDENT,
    IQTest,
    MAIL_SERVICE_COUNSELOR,
    ENROLLMENTS,
    VIEW_REGISTRATION,
    PAYMENTS,
    COURSES,
    GDSE,
    CMJD,
    DEP,
    RWAD,
    EMAILCOUNSILOR,
    EXAMS,
    SCHEDULE_EXAMS,
    SCHEDULE_IQTEST,
    ACADEMIC_STUDENTFORM,
    ACADEMIC_ADDIQMARKS,
    ACADEMIC_TRANSCRIPT,
    ACADEMIC_VIEW_RESULTS_BY_BATCH,
    ACADEMIC_MANAGE_EXAMS,
    ACADEMIC_VIEW_STUDENT_DETAILS,

    ACADEMIC_MANAGE_BATCHES,
    ACADEMIC_ADD_NEW_BATCH,

    SEND_MAIL_TO_REGISTERED

}